/**
 * Compose the generated `keewano-events.generated.ts` source from a
 * parsed event list. Two parts:
 *
 *   1. A typed wrapper function per event (`report{Name}`) that forwards
 *      to `Keewano.reportCustomEvent` with the event name and (for
 *      non-`None` events) the value. The wrapper signatures give the
 *      host compile-time type safety; the runtime resolves the name to
 *      its wire id and payload type from the `events` list below.
 *   2. A `customEventSet` export carrying the binary payload (gzip bytes
 *      + FNV-1a version stamp) for `/custom` registration AND the
 *      readable `events` list the runtime uses to emit.
 *
 * The output is deterministic: same `events` -> byte-identical TS
 * source. No timestamps, no nondeterministic byte literals.
 */

import type { BuildResult } from './types/buildCustomEventSet';
import type { EmitArgs } from './types/emit';
import type { CustomEventTypeValue, ParsedEvent } from './types/event';

import { buildCustomEventSet } from './buildEventsSet';
import { CUSTOM_EVENT_TYPE_NAMES } from './types/event';

const DEFAULT_SDK_MODULE_NAME = '@keewano/react-native-sdk';

/**
 * Per-type parameter list for the generated wrapper. Indexed by
 * `CustomEventTypeValue` so adding a new type forces this table to
 * compile (the `Record` key union enforces exhaustiveness). `None`
 * takes no argument and forwards no `value`.
 */
const WRAPPER_PARAM_BY_TYPE: Readonly<Record<CustomEventTypeValue, string>> = {
  0: '',
  1: 'value: string',
  2: 'value: number',
  3: 'value: boolean',
  4: 'value: Date',
  5: 'value: { x: number; y: number }',
  6: 'value: number',
};

function emitGeneratedSource({ events, sdkModuleName }: EmitArgs): string {
  const moduleName = sdkModuleName ?? DEFAULT_SDK_MODULE_NAME;
  const bytes = buildCustomEventSet(events);

  const sections = [
    renderHeaderComment(events),
    renderImports(moduleName),
    renderWrappers(events),
    renderSetExport(bytes, events),
  ];
  return `${sections.join('\n\n')}\n`;
}

function renderHeaderComment(events: readonly ParsedEvent[]): string {
  /**
   * `**\/*.generated.ts` is excluded from ESLint via the repo's root
   * `ignorePatterns`, so no per-file `eslint-disable` comment is
   * emitted here. The header is pure documentation.
   */
  const body =
    events.length === 0
      ? ' *   (no events defined)'
      : events
          .map((e) => ` *   ${e.id}  ${e.name}  (${CUSTOM_EVENT_TYPE_NAMES[e.type]})`)
          .join('\n');
  return [
    '/**',
    ' * AUTO-GENERATED by @keewano/codegen.',
    ' * DO NOT EDIT. Re-run `npx @keewano/codegen` to regenerate.',
    ' *',
    ' * Events (sorted ordinal-by-name; index determines wire id):',
    body,
    ' */',
  ].join('\n');
}

function renderImports(moduleName: string): string {
  return [
    `import type { CustomEventSet } from '${moduleName}';`,
    '',
    `import { Keewano } from '${moduleName}';`,
  ].join('\n');
}

function renderWrappers(events: readonly ParsedEvent[]): string {
  if (events.length === 0) {
    return '// (no custom events declared yet)';
  }
  return events.map(renderWrapper).join('\n\n');
}

function renderWrapper(event: ParsedEvent): string {
  const fnName = `report${event.name}`;
  const param = WRAPPER_PARAM_BY_TYPE[event.type];
  const forwardValue = param === '' ? '' : ', value';
  return [
    `export function ${fnName}(${param}): void {`,
    `  Keewano.reportCustomEvent({ name: '${event.name}'${forwardValue} });`,
    '}',
  ].join('\n');
}

function renderSetExport(bytes: BuildResult, events: readonly ParsedEvent[]): string {
  const versionLiteral = `0x${bytes.version.toString(16).toUpperCase().padStart(8, '0')}`;
  const gzipLiteral = formatBytesLiteral(bytes.gzipData);
  const eventsLiteral = renderEventsLiteral(events);
  return [
    'export const customEventSet: CustomEventSet = {',
    `  version: ${versionLiteral},`,
    `  eventCount: ${bytes.eventCount.toString(10)},`,
    `  gzipData: new Uint8Array(${gzipLiteral}),`,
    `  events: ${eventsLiteral},`,
    '};',
  ].join('\n');
}

function renderEventsLiteral(events: readonly ParsedEvent[]): string {
  if (events.length === 0) return '[]';
  const entries = events.map((e) => `    { name: '${e.name}', type: ${e.type} }`).join(',\n');
  return `[\n${entries},\n  ]`;
}

function formatBytesLiteral(bytes: Uint8Array): string {
  if (bytes.length === 0) return '[]';
  const tokens: string[] = [];
  for (const byte of bytes) {
    tokens.push(`0x${byte.toString(16).toUpperCase().padStart(2, '0')}`);
  }
  return `[${tokens.join(', ')}]`;
}

export { emitGeneratedSource };
